### ISSUE TITLE
3.2.  Confidential Machine Learning (ML) Model Protection (Guy)

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#176]
Why is ML any different from other proprietary value-add software, e.g. CAD layout, financial analysis algorithms, etc

**Comment by William-PanWei** [comment]
The confidential asserts provider needs to appraise the device whether it's trustworthy before providing the confidential assets. ML is just an example of confidential asserts, not the only example.

**Comment by William-PanWei** [comment]
I suggest "wontfix" this issue.

**Comment by dthaler** [comment]
Agree with William.  The use case right after the ML one already says it's a generalization of it.  But the ML model is a popular use case so worth calling out for folks who are looking for that in particular.  It's also worth keeping them separate since the ML model one is closer to confidential "code" vs the generalization about confidential "data" (though often the distinction between code vs data is blurry).

Adding wontfix label back to see if anyone disagrees.  (wontfix == email response but no change to doc)

**Comment by mcr** [comment]
People think confidential data needs to be "encrypted", but that confidential code needs to be obfuscated.  In fact, both just require confidentiality protection, with a similar solution.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
