### ISSUE TITLE
slight cognitive dissonance in the "Roles and Entities" section

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#235]
This sentence:
```
   An entity in the RATS architecture includes at least one of the roles
   defined in this document.
```
creates a bit of cognitive dissonance.

In the Terminology section, the Endorser, Ref-val Provider, RP Owner and Verifier Owner are defined as "entities", however, they don't include any of the roles (Verifier, RP, Attester).

**Comment by henkbirkholz** [comment]
That is a weirdly persistent bug that we have to squash once and for all.

Attester, Verifier, Endorser, RVP, RP, RP Owner, and Verifier Owner are all **roles**. Roles are instantiated by **entities**, which is the term we now use under the premisethat the well-established and understood term principal is to hard to understand for a reader (sry, got a bit rant'y here).

I think I added all the changes that fixes this issue to a PR that was abandoned at the end. It seems we missed to rescue my corresponding changes from that PR, though. Can anybody provide a pointer to these changes? Otherwise we have to dig that up in the next meeting.
