### ISSUE TITLE
RD AD review: vouching by endorser

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#359]
````
** Section 7.4.

   In a typical solution, a Verifier comes to trust an Attester
   indirectly by having an Endorser (such as a manufacturer) vouch for
   the Attester's ability to securely generate Evidence, in which case
   the Endorser's key material is stored in the Verifier's trust anchor
   store.

How does an Endorser "vouch" for something?
````

**Comment by nedmsmith** [comment]
"... vouch for the Attester's ability to securely generate Evidence by asserting endorsement claims regarding the ways in which attestation keys are protected. Consequently, the Endorser's key material is stored in the Verifier's trust anchor store so that Endorsements can be included in the Verifier's appraisal."

**Comment by henkbirkholz** [comment]
This proposal is definitely a step into the right direction. We should not overload this, but I think this is appropriately improved.

**Comment by nedmsmith** [comment]
"attestation keys are protected" is too narrow

**Comment by nedmsmith** [comment]
See PR #374
