### ISSUE TITLE
In Section 5.1, is it approriate to say that the attestation result is success or failure?

### ISSUE THREAD

**Issue by FrankXL** [ietf-rats-wg/architecture#37]
The more accurate text should be compliance or non-compliance.
And whatever the attestation result is, the attester should always present the attestation result to the relying party, I think.

**Comment by mcr** [comment]
>    In this model, an Attester sends Evidence to a Verifier, which
   compares the Evidence against its Appraisal Policy.  The Verifier
   then gives back an Attestation Result.  If the Attestation Result was
   a successful one, the Attester can then present the Attestation
   Result to a Relying Party, which then compares the Attestation Result
   against its own Appraisal Policy.

**Comment by mcr** [comment]
Prpposed text:

There are two ways in which the process may fail.  First, the Verifier may
refuse to issue the Attestation Result due to some error in processing, or
some missing input to the Verifier.
The second way in which the process mail is when the resulting Result is
examined by the Relying Party, and based upon the Appraisal Policy, the
result does not pass the policy.

**Comment by nedmsmith** [comment]
success with compliance
success with non-compliance
failure (implies non-compliance)
unavailable verifier (Implies non-compliance)
