### ISSUE TITLE
It seems to miss a final conclusion for the second paragragh in section 5.1

### ISSUE THREAD

**Issue by FrankXL** [ietf-rats-wg/architecture#39]
Since the resource access protocol between the Attester and Relying
Party includes an Attestation Result, in this model the details of
that protocol constrain the serialization format of the Attestation
Result. The format of the Evidence on the other hand is only
constrained by the Attester-Verifier attestation protocol. "So..."

**Comment by mcr** [comment]
>    Since the resource access protocol between the Attester and Relying
   Party includes an Attestation Result, in this model the details of
   that protocol constrain the serialization format of the Attestation
   Result.

Is it this sentence that is the problem?

**Comment by FrankXL** [comment]
Should we add the final conclusion as: "Since the Attestation Result is also one kind of Evidence, so the both the aformentioned two protocols would constrain the format of Evidence"?

**Comment by nedmsmith** [comment]
I don't think it is correct to assert that Attestation Results are 'a kind of Evidence'. Attestation Results are a statement of truth that is believed by Relying Party because the RP trusts whatever the Verify says about the Attester. It is wrong to position that Evidence and Results are the same because they (may) have the same claims / encodings.

**Comment by mcr** [comment]
@FrankXL , can you see if our latest text satisfies this concern, and if not, please re-open this issue.
