### ISSUE TITLE
Trust Model Section, Evidence consumed by an Endorser

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#57]
In the 2nd paragraph of the Trust Model section, the third sentence is impossible for me to make sense of. Which trust relationships are addressed here and why should an Endorser consume Evidence - even in the case that a Verifier "acts" (also not the best choice of words) as an Attester?

**Comment by William-PanWei** [comment]
The Endorser doesn't consume the Evidence directly, it takes on the role of Relying Party and consumes the Attestation Results of the Verifier which now takes on the role of Attester.
The purpose is to say the Verifier should be trusted by the Endorser. There should be another upper-level Verifier between the Endorser and the Verifier in this 'explicit way '

**Comment by nedmsmith** [comment]
The trust model should describe what each entity (in the capacity of a particular role) trusts the other entity to do (or not to do). In the context of Role messages, the direction the message flows is relevant to the trust model. An entity receiving a message is going to use the message to alter its behavior. The altered behavior has security relevance. Therefore, the trust model should describe the conditions in which acceptance of the message is warranted. For example, the Verifier accepts Endorsements from an Endorser because it believes the Endorser is an authority for asserting claims about how an entity was constructed, manufactured, tested, etc...

Trust in the opposite direction of the message flow is also relevant but from a privacy context. The Endorser trusts the Verifier to receive Endorsements to use them to satisfy appraisals (and not for other purposes such as marketing or advertising???). Though I don't know if it is appropriate for the arch document to speculate on this. But saying that Endorser trusts Verifier without qualification is useless. Therefore, shouldn't appear in the document IMO.

**Comment by henkbirkholz** [comment]
I assume, that at segregating this into permutation of examples is actually really helpful.

It might make readers better understand when "Attester --Evidence--> Relying Party" happens although a Verifer is defined as the consumer of Evidence. Would everybody agree with that? We could create a complete list of required examples here in the comments and then put them into the draft.
